### ISSUE TITLE
[Editor] Erroneous error message when using CSS custom properties

### ISSUE THREAD

**Issue by IshoAntar** [neocities/neocities#366]
When using CSS custom properties. e.g.
```css
body {
  --my-var: foobar;
}
```

An error message `Expected RBRACE at line X, col Y.` is displayed on the gutter, even though the code is correct.
