### ISSUE TITLE
Auto deploy site from GitHub

### ISSUE THREAD

**Issue by 3kh0** [neocities/neocities#384]
Is there a way I can link a Github repo to deploy it with Neocities? I am looking for an alternative to vercel.

**Comment by fu-sen** [comment]
You can do that with GitHub Action and [neocel](https://github.com/kognise/neocel).

**.github/deploy/deploy.yaml**:
```
name: Deploy Website
on: [push]
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - run: npm install -g neocel
      - run: neocel -t ${{ secrets.NEOCITIES_API_KEY }} -y
```

NEOCITIES_API_KEY can be obtained on the Web in addition to neocel.

If you use a static file generator, add `-d output-dir` to `neocel`. MkDocs example:
https://github.com/mkdocs/mkdocs/wiki/Mkdocs-Deployments#neocities
